spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:policy;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;MODE=Oracle;INIT=create schema if not exists DEMO\;
  sql:
    init:
      encoding: UTF-8
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: data.sql,ifrs17_gi_Act_init_pos_policy.sql
